databases:
  - name: jhonellapp
    databaseName: jhonellaapp
    user: jhonellaapp_user

services:
  - type: web
    name: jhonellaapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jhonellaapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false